# Generated by Django 4.1.5 on 2023-01-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_add',
            field=models.CharField(default=None, max_length=100, verbose_name='креатед_эд'),
            preserve_default=False,
        ),
    ]
